food/urls.py
from django.urls import path
from . import views

app_name = 'food'
urlpatterns = [
    path('',views.index, name='index'),
    path('<int:item_id>',views.detail, name='detail'),
    path('add',views.create_item, name='create_item'),
    path('update/<int:id>',views.update_item, name='update_item'),
    path('delete/<int:id>',views.delete_item, name='delete_item'),
]

foodapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('food.urls')),
    path('register/',include('users.urls')),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.register,name='register')
]

food/models.py
from django.db import models

# Create your models here.
class Item(models.Model):
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://www.thefuzzyduck.co.uk/wp-content/uploads/2024/05/image-coming-soon-placeholder-01-660x660.png")
    item_prep = models.TextField(default='there is no data on this item')

    def __str__(self):
        return self.item_name

users/models.py
from django.db import models

# Create your models here.

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        # fields = ['item_name','item_desc','item_price','item_image']
        fields = '__all__'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

food/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm

# Create your views here.
def index(request):
    item_list = Item.objects.all()
    context = {
        'item_list' : item_list,
    }
    return render(request,'food/index.html',context)


def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request,'food/detail.html',context)


def create_item(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

def update_item(request,id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)

    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form,'item':item})


def delete_item(request,id):
    item = Item.objects.get(id=id)

    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'welcome {username}, your account is created')
            return redirect('food:index')
    else:
        form = RegisterForm()
    return render(request,'users/register.html',{'form':form})

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>index</title>
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'food:index' %}">FoodApp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
                aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav mx-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'food:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'food:create_item' %}">Add Item</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Delete</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">View</a>
                    </li>
                </ul>
                <!-- <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form> -->
            </div>
        </div>
    </nav>

    {%if messages %}
        {% for message in messages %}
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

    {% block content %}
    <div class="container">
        <div class="row mt-4">
            <div class="col-12">
                <img src="{{ item.item_image }}" height="200" class="img-fluid mx-auto d-block" alt="">
            </div>
            <div class="col my-4">
                {{ item.item_prep }}
            </div>
            <div class="col-12 my-3">
                <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger">delete</a>
            </div>
        </div>
    </div>
    {% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}

    {% block content %}
    <div class="container-fluid my-5">
        {% for item in item_list %}
        <div class="row mb-4">
            <div class="col-md-3 offset-md-2">
                <img src="{{ item.item_image }}" class="card img-fluid" height="150px" alt="">
            </div>
            <div class="col-md-4">
                <h2 class="h2">{{ item.item_name }}</h2>
                <h2 class="h2">{{ item.item_desc }}</h2>
                <h2 class="h2"> &#8377; {{ item.item_price }}</h2>
            </div>
            <div class="col-md-2">
                <!-- <a href="{% url 'food:detail' item.id %}" class="btn btn-primary">view</a> -->
                <div class="d-grid gap-2 d-md-block">
                    <a href="{% url 'food:detail' item.id %}" class="btn btn-success" type="button">details</a>
                    <a href="{% url 'food:update_item' item.id %}" class="btn btn-primary" type="button">edit</a>
                </div>
            </div>
        </div>
        
        {% endfor %}
    </div>
    {% endblock %}

food/templates/food/item-delete.html
{% extends 'food/base.html' %}

    {% block content %}
    <div class="container">
        <form method="POST" class="mt-4">
            {% csrf_token %}
            <h2>Are you sure you want to delete {{ item.name }}</h2>
            <button type="submit" class="btn btn-danger">confirm</button>
        </form>
    </div>
    
    {% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}

    {% block content %}
    <div class="container">
        <form action="" method="POST" class="mt-4">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
    
    {% endblock %}

users/templates/users/register.html
{% extends 'food/base.html' %}

    {% block content %}
    <div class="container">
        <form method="POST" class="mt-4">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Sign up</button>
        </form>
    </div>
    
    {% endblock %}